services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: studentdb
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  studentmanagement:
    image: waelbti/student-management:latest
    depends_on:
      - db
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/studentdb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_SERVLET_CONTEXT_PATH=/student
    restart: unless-stopped

volumes:
  db_data:
