apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-management-ingress
  namespace: student-management
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: student-management.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: student-management
                port:
                  number: 8089
