apiVersion: v1
kind: Service
metadata:
  name: student-management-service
  namespace: student-management
spec:
  type: NodePort
  selector:
    app: student-management
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30089
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
  namespace: student-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
      - name: student-management
        image: waelbti/student-management:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /student/students/getAllStudents
            port: 8089
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /student/students/getAllStudents
            port: 8089
          initialDelaySeconds: 30
          periodSeconds: 5
