apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: student-management
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "rootpassword"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SERVER_SERVLET_CONTEXT_PATH: "/student"
